# Generated by Django 3.0.6 on 2020-05-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200523_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='content',
            new_name='context',
        ),
    ]
